### ISSUE TITLE
タイポグラフィ：「外観」のフォントの太さが全て反映されない

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#100]
タイポグラフィパネルに「外観」が追加され、フォントの太さが100～900の9段階で設定出来るようになった。
日本語フォントで全ウェイトに対応するのは非現実的だと思うので、不具合というよりはスルーでも良いと思います。

![capture](https://user-images.githubusercontent.com/54422211/149295984-22590197-828f-4377-be83-55ae0b28e536.png)

**Comment by ddryo** [comment]
これはスルーで行きます！
