### ISSUE TITLE
「行」ブロックの扱いについて

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#124]
WordPress5.9で追加される、グループブロックのバリエーションである「行」ブロックをサポートするかどうか。

Related: https://github.com/loos/SWELL/issues/109

**Comment by ddryo** [comment]
`wp-container-{id}`クラスで行としてのスタイルがあたっていて、「行」に対しての調整ができないですね...。

<img width="328" alt="スクリーンショット 2022-01-21 17 21 21" src="https://user-images.githubusercontent.com/31400297/150492689-84c9a663-57ee-40e5-886e-243cb3cf9140.png">

<img width="560" alt="スクリーンショット 2022-01-21 17 21 27" src="https://user-images.githubusercontent.com/31400297/150492693-4cce2b0c-c64a-42fd-8b35-93c4b8dedcd3.png">

# 発生している問題
以下のように、マージンを調整しているスタイルと併用すると崩れている

<img width="806" alt="スクリーンショット 2022-01-21 17 21 30" src="https://user-images.githubusercontent.com/31400297/150492818-3d877c6e-993b-440f-9705-0d799feed683.png">

**Comment by ddryo** [comment]
issue 立てました
https://github.com/WordPress/gutenberg/issues/38126
