### ISSUE TITLE
グループブロック等の wp-container-{id} クラスを停止させたい

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#126]
<img width="421" alt="スクリーンショット 2022-01-21 17 24 17" src="https://user-images.githubusercontent.com/31400297/150492372-bd746ad7-f9a1-4e10-896f-ac77d9519f5b.png">

このクラスでスタイルがあたっているため、「行」ブロックを判定して調整することができない。（#124 の問題を修正できない）

**Comment by t-hamano** [comment]
### フロントエンド側

PHP側で、render_blockにフックしてクラス追加・styleタグを出力しているようです。
https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/block-supports/layout.php#L168-L176

なので、テーマ側でさらに `render_block` して、`wp-container-XX` を `preg_replace` で消す事は出来そうです。

また、行ブロックか普通のグループブロックを判定するには、`$block['attrs']['layout']`を見ればよさそうです。
https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/block-supports/layout.php#L168-L176

これを見て、`render_block` に行の場合のクラスを追加しても良いと思います。

### エディター側

`attributes.layout` で判断出来るので、JS側の `addFilter` で行の場合のクラスを追加出来るかもしれません。
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/group/variations.js#L11

**Comment by ddryo** [comment]
- `wp-container-{id}`クラスはボタンやソーシャルアイコンでも吐き出される。
- → flexで「レイアウト」パネルが利用できるブロック？

**Comment by ddryo** [comment]
> また、行ブロックか普通のグループブロックを判定するには、$block['attrs']['layout']を見ればよさそうです。
これを見て、render_block に行の場合のクラスを追加しても良いと思います。

これでいけそうですね！ありがとうございます！
もう少しコアの動向を様子見しつつ、行を使いたい要望が挙がってきたりしたらこれで対応します！
