### ISSUE TITLE
バナーリンクブロック：バナーエリアが背景画像で埋められない

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#135]
バナーの高さを明示的に指定し、背景画像がその高さに満たない場合に余白が出来る。
もし仕様通りでない場合は、`object-fit` を入れた方がよいかもしれません。

![capture](https://user-images.githubusercontent.com/54422211/150740836-aa22489b-7819-49b0-92fe-7369a1959fec.png)

**Comment by ddryo** [comment]
<img width="1345" alt="スクリーンショット 2022-01-25 23 55 32" src="https://user-images.githubusercontent.com/31400297/151000466-0b2c90b9-8761-4086-90a2-d297c539d95a.png">

再現できずでした...！
これってフロント側でも発生していますか？

**Comment by ddryo** [comment]
あれ、ホントですね！どこかのアップデートでobject-fit消えちゃってたっぽいです...
