### ISSUE TITLE
項目ラベルの余白

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#146]
`BaseControl.VisualLabel`の下が詰まって見えるので、他のコントロール系のラベルにあわせて、`margin-bottom: 8px` 入れてはどうかと思いました。

※もしくは、`BaseControl.VisualLabel` を使わずに `<BaseControl label="Text">` みたいにする

![1](https://user-images.githubusercontent.com/54422211/150757319-881d0496-adbc-44f8-bc16-dee7186718e9.png)

**Comment by ddryo** [comment]
あら、ここ他のブロックで確認したらmarginあったのでちょっと前にCSS削除しちゃってました。`BaseControl.VisualLabel`使っているところにはまだ必要みたいですね、戻しておきます。
発見ありがとうございます！！

（たしか以前は`label`使えなかったのですが、今使えるんですね！）

**Comment by ddryo** [comment]
あ、やっぱlabelだめでした

<img width="996" alt="スクリーンショット 2022-01-25 23 46 33" src="https://user-images.githubusercontent.com/31400297/150998818-6e2b8c52-d751-4e5a-8b94-e4f8bd059bce.png">
