### ISSUE TITLE
デバイスプレビューを切り替えると、タイトル文字数カウントが消える

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#147]
おそらく、この辺りのイベント発火方法の変更と、window指定を相対指定（`defaultView`）に変える必要があると思われる。

https://github.com/loos/SWELL/blob/689b771aaaa604609bd838bc8e73885a70f31999/src/js/admin/count_title.js#L31-L41

**Comment by ddryo** [comment]
プレビュー時に文字数カウントいらないので、とりあえずスルーでいきます
