### ISSUE TITLE
関連記事ブロック：モバイル/タブレットプレビューでレイアウトが崩れる 

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#148]
- リスト型：記事下に大きな余白が出来る
- サムネイル型：記事タイトル部がはみ出る
- テキスト型：記事下に大きな余白が出来る

![リスト型](https://user-images.githubusercontent.com/54422211/150763234-9057415a-d342-4b56-82a0-a1a8197c8721.png)

![サムネイル型](https://user-images.githubusercontent.com/54422211/150763251-6b898742-c77b-4732-af49-05da69cfde9e.png)

![テキスト型](https://user-images.githubusercontent.com/54422211/150763267-88f6db4d-bcff-4594-a32c-f0b55f243635.png)

**Comment by ddryo** [comment]
▼ 関連
https://github.com/loos/arkhe-blocks-pro/issues/31
