### ISSUE TITLE
グループのバリエーション（行・縦積み）をどうするか

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#258]
```
domReady(() => {
	unregisterBlockVariation('core/group', 'group-row');
	unregisterBlockVariation('core/group', 'group-stack');
});
```

でオフにしても、wp60以降ツールボタンからは使用できてしまう。

<img width="400" alt="スクリーンショット 2022-05-20 16 58 44" src="https://user-images.githubusercontent.com/31400297/169484145-042a7d14-6933-4f1e-a8ca-02fd9d7bf2ae.png">

**Comment by ddryo** [comment]
```
remove_filter( 'render_block', 'wp_render_layout_support_flag' );
```
で邪魔な`wp-conttainer-`系クラスとスタイルを削除できるが、そうするとグループバリエーションには`is-row`などの識別クラスがないため、スタイルを調整することができなくなる。

→ レンダーフックでバリエーションを調べて、クラスを付与するか？

**Comment by t-hamano** [comment]
> domReady(() => {
> 	unregisterBlockVariation('core/group', 'group-row');
> 	unregisterBlockVariation('core/group', 'group-stack');
> });
> でオフにしても、wp60以降ツールボタンからは使用できてしまう。

issue立てました。
https://github.com/WordPress/gutenberg/pull/39710

**Comment by t-hamano** [comment]
@ddryo 
以下PRにて解決したようです。
https://github.com/WordPress/gutenberg/pull/41305
バックポートはされないようなので、修正されるのはWordPRess6.1だと思います。
