### ISSUE TITLE
onChangeCompleteのチェック

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#47]
<ColorPicker>のonChangeComplete→onChangeに変わる。
https://make.wordpress.org/core/2022/01/04/miscellaneous-block-editor-changes-in-wordpress-5-9/

**Comment by t-hamano** [comment]
- 5.9では、`onChangeComplete` の `color` プロパティが無くなる。
- `ColorPicker` コンポーネントを使っている場合のみ影響あり。`ColorPalette` や `PanelColorGradientSettings`などは影響無し。

**Comment by t-hamano** [comment]
以下プルリクを見る限り、Gutenberg 11.8で `onChange` への変更が取り込まれたようだが、5.9 RC1では発動しない。
また、`onChangeComplete` を消すとエラーとなる。
https://github.com/WordPress/gutenberg/pull/35220

**Comment by t-hamano** [comment]
- `ColorPicker` コンポーネントの `props` によって、振る舞いが変わる模様。
- `disableAlpha` が非推奨になり、enableAlpha（デフォルトはfalse）に変わった。（https://github.com/WordPress/gutenberg/blob/81015b0089ff26ffdd9694f627ad08b2723dae09/packages/components/CHANGELOG.md#enhancements-3）
- `disableAlpha` を `props` として付与していると、レガシーカラーと判定され、`onChange` が発動しない。（https://github.com/WordPress/gutenberg/blob/9faa63ec01c7db4e4d57823af2db5c54bb6d6660/packages/components/src/color-picker/stories/index.js#L65-L69）
- 5.8 / 5.9で、disableAlphaの付与を切り分ける必要あり？

**Comment by t-hamano** [comment]
ここはもう少し調べる必要がありそうなので、一旦対応は後回しとする。

**Comment by ddryo** [comment]
今回はとりあえずスルーでいきます！

memo: レガシーコンポーネントの互換サポートが切れた頃に修正
