### ISSUE TITLE
ギャラリーブロックの構造変更への対応

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#48]
See: https://make.wordpress.org/core/2021/08/20/gallery-block-refactor-dev-note/

**Comment by t-hamano** [comment]
メモ：

- ギャラリーブロックと画像ブロックのUIに一貫性がなかった
- ギャラリーブロックがInnerBlocks化され、子に画像ブロックを持つようになった（https://github.com/WordPress/gutenberg/blob/release/11.9/packages/block-library/src/gallery/gallery.js#L16-L35）
- そのため、画像ブロックに追加された機能（スタイル等）も、ギャラリーブロック内の画像ブロックにも反映される
- DOM構造が変わるため、旧セレクタを残しつつ新セレクタを追加する必要がある
- 5.9アップデート後、新しく追加されたギャラリーブロックだけが新構造になる？（要検証）
- フィルターフックの動作確認（`render_block_core/gallery`、`render_block_core/image`）
- javascriptで、ギャラリーブロックのセレクタを使って処理している箇所がないかチェック

**Comment by t-hamano** [comment]
検証結果：
- 5.8でギャラリーブロックを投入し、5.9にアップデートすると、新ギャラリーブロックに移行される。
- フロントエンド側は、その記事を保存したタイミングで新ギャラリーブロックのHTML構造にアップデートされる。

**Comment by ddryo** [comment]
- 「クリックして拡大する機能」がギャラリーブロックとインナーの画像ブロックそれぞれで設定できてしまい、設定がうまく機能していない
- 「ブラウザ風」と「デスクトップ風」スタイルが崩れてしまう

**Comment by ddryo** [comment]
# DOM変化

```
figure.wp-block-gallery.columns-3.is-cropped
  ul.blocks-gallery-grid
    li.blocks-gallery-item
      figure
        img
```

```
figure.wp-block-gallery.has-nested-images.columns-default.is-cropped
  figure.wp-block-image
    img
```

- .has-nested-imagesが付いているものが、5.9以降に設置（変換）されたもの。
- ギャラリー初期配置時、`.columns-3`などではなく`.columns-default`がつくようになった。

**Comment by ddryo** [comment]
@t-hamano
ギャラリーブロック内の画像ブロックには

**Comment by ddryo** [comment]
memo: ギャラリー内の画像ブロックには`BlockAlignmentControl`が表示されないので、親ブロックを判定してコントロールしているのかと思い、もしそうならその方法でSWELL独自の設定も非表示にしたかったが、

おそらく
[gallery.js内の__experimentalLayout](https://github.com/WordPress/gutenberg/blob/fa8234448e8df5dbd0670e0fc395b71102d47eb4/packages/block-library/src/gallery/gallery.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L34)
で`alignments`を空に指定している部分でコントロールしている。
