### ISSUE TITLE
「Custom header image attributes」忘れずに検証する。

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#52]
SWELLでは影響ないかもしれないがArkheで影響あるかもしれない。。

https://make.wordpress.org/core/tag/dev-notes+5-9/

**Comment by t-hamano** [comment]
## 概要

- 5.8では、カスタムヘッダー画像のaltタグは必ずサイトタイトルになる（https://github.com/WordPress/wordpress-develop/blob/5.8/src/wp-includes/theme.php#L1209）
- 5.9では、カスタムヘッダー画像のaltタグはデフォルトでempty、画像にaltテキストが設定されていればそれを出力するようになった（https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/theme.php#L1196-L1205）
- 以下関数を使っている場合に影響あり。
    - `get_header_image_tag()`
    - `the_header_image_tag()`
    - `get_custom_header_markup()`
    - `the_custom_header_markup()`

SWELLでは上記いずれの関数も使っていないため、対応不要。
