### ISSUE TITLE
RSS widgetのクラス名が変わる？

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#53]
See: 「Legacy RSS widget feed icon link」](https://make.wordpress.org/core/2022/01/07/theme-focused-changes-and-filters-in-wordpress-5-9/#legacy-rss-widget-feed-icon-link)

**Comment by t-hamano** [comment]
タイトル部のHTMLが以下のように変わる。

### 5.8

```html
<!-- RSSアイコンリンク -->
<a class="rsswidget" href="#">
	<img class="rss-widget-icon" style="border:0" width="14" height="14" src="{rsslink}" alt="RSS">
</a>
<!-- テキストリンク -->
<a class="rsswidget" href="#">
	{title}
</a>
```

### 5.9

```html
<!-- RSSアイコンリンク -->
<a class="rsswidget rss-widget-feed" href="#">
	<img class="rss-widget-icon" style="border:0" width="14" height="14" src="{rsslink}" alt="RSS">
</a>
<!-- テキストリンク -->
<a class="rsswidget rss-widget-title" href="#">
	{title}
</a>
```

これまでは、どちらのaタグも同じクラス名だったが、それぞれを判別するための `.rss-widget-feed`、`.rss-widget-title` クラスが付与された。
これにより、RSSアイコン・テキストそれぞれをスタイリングしやすくなった。

SWELLでは、アイコン・テキストでそれぞれ個別にスタイルは当てておらず、また5.8/5.9でも見た目は変わらないため、対応不要。
