### ISSUE TITLE
全てのブロックでフォントサイズが全体的に大きく表示される

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#54]
`.editor-styles-wrapper`のfont-sizeが `medium → 18px`に変わった事が原因。

![148532846-18ee9519-3e6d-47c1-8264-d2d063d7a704](https://user-images.githubusercontent.com/54422211/148635175-5a8ed0fd-c651-4009-8f6e-1248ccfb9f3c.png)

エディター側にも、`font-size: var(--swl-content_font_size,16px);`を当てる必要あり？

![148532897-e283ffaf-70f2-45f0-bbab-efb69415f549](https://user-images.githubusercontent.com/54422211/148635178-bf036ebf-8b51-46a2-b55a-488d4983b31a.png)

**Comment by ddryo** [comment]
> エディター側にも、font-size: var(--swl-content_font_size,16px);を当てる必要あり？

これ、現在あたってないのが不具合ですね...。

僕の方で修正しておきます！
