### ISSUE TITLE
幅を狭めた時にブロックの左右に余白がつかない

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#56]
`.editor-styles-wrapper` の `padding:8px`が無くなったため

![148532927-2297e10e-e78c-4d8d-9925-b92910dcb42a](https://user-images.githubusercontent.com/54422211/148635227-fd653235-488b-4481-aac8-336615e7fc31.png)

**Comment by ddryo** [comment]
これRC2で改善されてるっぽいです！

**Comment by ddryo** [comment]
memo: RC2でpadding復活してるので修正用CSS削除する
