### ISSUE TITLE
プレビューを「モバイル→デスクトップ」と切り替えると、メタボックスがコンテンツトップにきて被ってしまう

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#59]
コアの問題

![148533007-b3a9d8a8-ef1f-477f-b9bd-4a6b9670c07a](https://user-images.githubusercontent.com/54422211/148635299-4de0711c-48e4-4c01-9c27-934faea0b235.png)
？

**Comment by ddryo** [comment]
これ5.8くらいから発生しているバグのようで、windows限定バグっぽいです...。おそらくコアの問題なので、一旦放置でお願いします！

**Comment by ddryo** [comment]
5.9からはMacでも発生することを確認しました。

memo：あとでgutenbergにissue立てる

**Comment by t-hamano** [comment]
@ddryo 
issue立てました。
https://github.com/WordPress/gutenberg/issues/38062

**Comment by ddryo** [comment]
ありがとうございます！
