### ISSUE TITLE
「投稿」タブの「SWELL設定」パネルが狭くなっている

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#63]
`padding` の当たり方が変わったことが原因。

![148533071-3d66c0e7-0fa7-4154-b61c-a06ad05f9945](https://user-images.githubusercontent.com/54422211/148635388-e4bcdc79-1875-4bce-8e86-b5c95750506f.png)

**Comment by t-hamano** [comment]
以下のコミットで、padding周りに調整が入った事が原因。
https://github.com/WordPress/gutenberg/pull/36297/files#diff-07d2e80cd03485211d5081c630d6a5410ed9215cc565073c5ce7a1e2c363f6c0L37-L52

おそらく、metabox（PluginsSidebar）がサイドバーに設置された時のスタイリングが漏れているので、PRを送った方が良いかもしれない。

**Comment by t-hamano** [comment]
以下でボタンサイズを小さくしている事が原因かもしれないので、再オープン。
5.8/5.9両方でサイドテストしてみる。

https://github.com/loos/SWELL/blob/2b58d99d652a6a4bfe5ed61cb5692c9d1920721f/src/scss/editor/gutenberg/_sidebar.scss#L7-L9

**Comment by t-hamano** [comment]
最終的に、5.8/5.9でレイアウトを維持するために幅のみ`44px → 28px`に変更し、[その他調整](https://github.com/loos/SWELL/commit/87ed03b8e7d3c276b3a9bdbc61ad4f37fed3bb5c#r63208067)を加えた。

![capture](https://user-images.githubusercontent.com/54422211/148732256-d70eb3ae-a155-4cdb-a1cc-23e84f3caa85.png)

5.9で、カーソルにフォーカスを当てた時に下部のアウトラインが見切れるのは5.9の仕様（不具合？）と思われます。

**Comment by ddryo** [comment]
アイコンの位置がずれるのはコアの`top: .11rem`っぽかったのでこれを`0`にするだけにしました。
