### ISSUE TITLE
カバーブロック：テキスト色・フォントサイズが違う

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#65]
![148533112-a3a16e2c-19fd-4bde-ac50-f682cf188f22](https://user-images.githubusercontent.com/54422211/148635432-c2ede3f5-31c2-4502-acbf-808f72de023c.png)

**Comment by t-hamano** [comment]
フォントサイズに関しては、#57 同様、フォントサイズバリエーションがコア側でグローバル変数で上書きされてしまっている事が原因。

**Comment by t-hamano** [comment]
背景画像の濃さを見て、ブロックに `is-light` または `is-dark-theme` クラスが付与され、文字色も `#fff /#000` と切り替わるようになった。
後方互換のため、文字色は `#fff` で統一します。

**Comment by ddryo** [comment]
WordPress5.8まではカバーブロックのフォントカラーは白で固定だったが、5.9からは背景の色が明るい（と判断された）場合に`is-light`クラスが付き、それによってフォントが黒になっているようです。


この判定がなんとも微妙で、オーバーレイカラーの不透明度が50以下では「背景が明るい」と判定されてしまうようです。

https://user-images.githubusercontent.com/31400297/150265023-6620fb4c-e1d0-4161-a37a-1a8c5b7b932e.mp4

**Comment by ddryo** [comment]
【検証したこと】
- オーバーレイの色が「白」のときはずっとis-lightがついた。
- その他のテーマ側で用意している薄い色の場合は、境界線は ~50/60~ で黒と同じ。

**Comment by ddryo** [comment]
<img width="994" alt="スクリーンショット 2022-01-20 12 19 04" src="https://user-images.githubusercontent.com/31400297/150266184-96ffbbe5-9410-4f9c-9c44-3f68c19f28b5.png">

**Comment by ddryo** [comment]
これまでと同様、無理やり「白」に固定させることもできるが、そうすると逆にCSSでテキストを黒にしている場合などに影響がでそうなので、一旦、これは「コアの仕様変更」ということでテーマ側の追加対応はなしでいきます。

これによって「今まで白だったところが黒になってしまったので、白にしたい」場合、

カバーブロック自体にテキストカラーの設定がないので、中に配置した各段落ブロックなどに対してテキストカラーを指定する必要がある

というのが非常に不便な点ではあるので、あとでissue立ててみようと思います。

**Comment by t-hamano** [comment]
Arkheの方は、白固定で対応してしまっていたので、Revertします！
https://github.com/loos/arkhe/issues/19#issuecomment-1014111396
