### ISSUE TITLE
カスタムHTMLブロック：スタイルが若干変わった

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#66]
![148533148-e840f5db-25e4-4731-91ee-cedc6b845736](https://user-images.githubusercontent.com/54422211/148635459-8bd8ba03-f929-4b90-857e-16733d395eea.png)

**Comment by ddryo** [comment]
memo: 全部を5.8に戻す必要はないので、ボーダーカラー以外は後で消す
