### ISSUE TITLE
SWELLブロック全般：__experimentalUseInnerBlocksProps を使ったブロックが全て壊れる

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#67]

**Comment by t-hamano** [comment]
@ddryo 
save側で `useInnerBlocksProps.save()`を使うと、WordPress5.8ではエラーになってしまいますね。。
条件分けで `useInnerBlocksProps.save()` と `<InnerBlocks />` を切り分けても良いのですが、`InnerBlocks`は非推奨になったわけではないので、save側はそのままでも良いような気がします。

**Comment by ddryo** [comment]
@t-hamano 
なるほどです！ですね、ではsaveはそのままでいきます！

**Comment by t-hamano** [comment]
@ddryo 
了解です！
ではこれでクローズとします。
