### ISSUE TITLE
モバイルプレビューに切り替えると、スタイルが一切当たらない

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#68]
CSSの読み込み方が問題？

![148532985-daaaf85b-bfa6-4955-849f-7540ef644f83](https://user-images.githubusercontent.com/54422211/148635531-c7ab83e4-e328-4be3-a117-1acfd5cce34d.png)

**Comment by ddryo** [comment]
もともとここのプレビュー画面にはメディアクエリが効かなくて使い物にならず放置気味だったのですが、全く読み込まれないのは困りましたね...。

@t-hamano 
もしよければTwenty Twenty系での読み方の調査をお願いしたいです。

**Comment by t-hamano** [comment]
@ddryo 
Twenty Twenty Oneでは問題ありませんでした。

Mobile / Tabletのプレビューがiframe化されて、CSSが読み込まれなくなった事が原因かと思います。

Mobile/Tablet/Desktop Previews do not work with externally loaded CSS
https://github.com/WordPress/gutenberg/issues/21193

上記で了さんもコメントされていますが、`enqueue_block_editor_assets` で読み込んだCSSはiframe内に適用されないのでは、と思います。

**Comment by ddryo** [comment]
@t-hamano これってどう読み込むのが正解か分かりますか...？

**Comment by t-hamano** [comment]
@ddryo 
コンソールログに
```
For themes, use add_editor_style
```
と書いてあるので、ブロックに関するスタイルを切り出して`add_editor_style`すれば反映されるのではないかと思います。
ただそうなると、`.editor-styles-wrapper`や詳細度の調整が必要で全体に影響も出るので、かなり大変ですね。。

**Comment by t-hamano** [comment]
概要を #84 に集約したため、当issueはクローズします。
