### ISSUE TITLE
リッチカラムブロック：インサーターのレイアウト崩れ

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#70]
![rich-column](https://user-images.githubusercontent.com/54422211/148636624-7e76ae43-708c-47ab-a88f-6cc7b031402f.png)

**Comment by t-hamano** [comment]
リッチカラムブロックに限らず、`.block-editor-button-block-appender`を幅広表示しているInnerBlocksを持つ全てのブロックで発生。

**Comment by t-hamano** [comment]
`.block-editor-button-block-appender`のコアのスタイルが変わった事が原因。

- `margin`がコアのスタイルで上書きされてしまっている
- `position: absolute`で配置されるようになった

![capture](https://user-images.githubusercontent.com/54422211/148734134-40e4e899-3cb6-42f4-a6b1-7346e8e8e62c.png)

**Comment by ddryo** [comment]
memo: 
- faqブロックが未修正(他にもあるかも)。
- あとでまたこの部分のCSSが変わる可能性も高いので、一箇所にまとめて書く。
- staticではなくrelativeで

**Comment by ddryo** [comment]
memo: block-appenderのCSS変更により明らかに操作面で不便になっているので、まだコア側の調整入りそう。
しばらく要注意。
