### ISSUE TITLE
ブロックエディターにおけるCSS読み込みのブラウザNoticeエラー

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#77]
ブロックエディター上で、以下のようなCSS読み込みエラーが表示される。

![css](https://user-images.githubusercontent.com/54422211/148639545-acbd4e83-ff2c-427d-baec-b66042393576.png)

SWELL設定等、ブロックエディター以外では表示されない。

**Comment by t-hamano** [comment]
概要を #84 に集約したため、当issueはクローズします。

**Comment by ddryo** [comment]
@t-hamano 
このエラー、機能は僕の方でも見れていたのですが今日はなぜか表示されなくなりました...。
浜野さんの方ではまだ確認できますか？
