### ISSUE TITLE
モバイル・タブレットのプレビュー、ブロックパターン・ブロックスタイルのプレビューにスタイルが当たらない

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#84]
以下と関連

- #60
- #68
- #77

## 症状

- 「ブロックパターンプレビュー」「デバイスプレビュー（モバイル/タブレット）」「ブロックスタイル」に、テーマ側で追加したスタイルが当たらない。
- ブラウザコンソールログに `Stylesheet  was not properly added.～` というWarningログが出力される。

## 原因
- 5.9では、「ブロックパターンプレビュー」「デバイスプレビュー（モバイル/タブレット）」「ブロックスタイル」がiframe化される（将来的にはエディター部分も全てiframe化される）。
- `enqueue_block_editor_assets` で追加されたスタイル・スクリプトは、iframe内には読み込まれない。
- `hook_admin_head` で出力しているインラインCSS（ `loos-block-style` ）も、同様にiframe内には読み込まれない。

## 公式の見解

- ブロックに関わるスタイルは、`add_editor_style` で追加するべき。
- `enqueue_block_editor_assets` は、エディターコンテンツ以外のブロックエディター全体のUIのスタイルをコントロールするためだけに使用されるべき。
- 現状は、iframe内のコンテンツにインラインCSSを出力する手段がない。
- iframe内のコンテンツにインラインCSSを出力する方法として、`add_editor_style` に紐づく `wp_add_inline_style` のようなAPI開発が検討されている。

## 対応方針

- コンテンツ以外のブロックエディター全体のUIに関わるスタイルを `enqueue_block_editor_assets` に、ブロックに関わるスタイルを`add_editor_style`に切り分ける。
- インラインCSS（CSS変数）は、ハック的な方法になるが、`block_editor_settings_all` の `$settings['styles']` に追加する。（https://github.com/WordPress/gutenberg/issues/33212#issuecomment-885781142）

## 参考資料

- [Iframed Content Roadmap](https://github.com/WordPress/gutenberg/issues/33346) 
- [Warning when enqueuing styles for a plugin in iframed Full Site Editor](https://github.com/WordPress/gutenberg/issues/33212)
- [Blocks in an iframed (template) editor](https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/)

**Comment by ddryo** [comment]
浜野さんのおっしゃるとおり、block_editor_settings_all 使うしかないかもですね...。

エラさんが紹介？もしていますし...。

https://github.com/WordPress/gutenberg/pull/35950

**Comment by t-hamano** [comment]
@ddryo 
ですね。。
現状、iframe化されたエディターインスタンスにインラインCSSを読み込むにはそのやり方しかないと思います。
※将来的には、`add_editor_style`にハンドル名を持たせて、`wp_add_inline_editor_style`みたいなのが出来るかもです。

今日自分のプラグインで試していたのですが、インラインCSSに関してはそれでいけそうです！

https://github.com/t-hamano/richtext-extension/blob/wp5.9/inc/class-enqueue.php#L25-L26
https://github.com/t-hamano/richtext-extension/blob/wp5.9/inc/class-enqueue.php#L76-L83

**Comment by ddryo** [comment]
やることメモ

- コンテンツ（ブロック）に対するスタイリングと、それ以外の設定画面用のCSSをしっかり切り分ける。
- 前者のスタイルは`add_editor_style()`で読み込む。`add_theme_support( 'editor-styles' );`も追記する必要あり。
- 現在はadd_theme_supportせずにTinyMCE用にのみ`add_editor_style()`を使用しているので、TinyMCEの表示チェックも必要
- カスタマイザーの設定などを受けてインライン出力する必要のあるCSSは `block_editor_settings_all` を使用する。

**Comment by t-hamano** [comment]
ブロックスタイルに関しては、

- ブロック個別のスタイル（iframeインスタンス内にも適用させたいスタイル）をadd_editor_styleに
- iframeインスタンス内には不要な、ブロックエディター全体のスタイル（サイドバーのUIスタイル等）を、今まで通りwp_enqueue_styleに
という感じになると思います。

少しテストしたものを別ブランチでpushしましたので、よろしければご確認下さい。
https://github.com/loos/SWELL/commit/0cd443a690667f61724acbd556e85f38107b5bb0
※確認されたら、ブランチは削除されて大丈夫です。

**Comment by ddryo** [comment]
memo:

'admin_enqueue_scripts'で読み込んだCSSはモバイルプレビュー等でも読み込まれるが、コンソールに警告がでる。
逆に不用なものをiframe内に読み込まれないように条件分岐の追加が必要

**Comment by ddryo** [comment]
memo:
浜野さんがつぶやいていたように（https://twitter.com/tetsuaki_hamano/status/1481642719512772608?s=20）、コアのブロック用のハンドルに紐付けるのもあり。

絶対に読み込まれるであろうparagraphとかに紐付けてもいいかもしれない

**Comment by t-hamano** [comment]
memo

以下みたいに、エディター本体のハンドルに紐づける方法でもいけました！
（もっと良いハンドルがあるかもしれません）
```php
function add_inline_css() {
  wp_add_inline_style( 'wp-edit-blocks', 'p{background: red;}' );
}
add_action( 'init', 'add_inline_css' );
```

**Comment by ddryo** [comment]
【未解決の問題】

'admin_enqueue_scripts'で読み込まれるCSSがiframeで読み込まれてしまって、それに対して警告が出る。

<img width="535" alt="スクリーンショット 2022-01-14 16 05 36" src="https://user-images.githubusercontent.com/31400297/149465896-8586022a-65af-4867-a61e-f5096bde8efd.png">

ブロックウィジェットでの似たような問題は`IFRAME_REQUEST`等を使って対策できたが、今回の問題は`IFRAME_REQUEST`で判定はできなかったので、何かしら他の方法を探さないといけない。（もしくは、なにかいい方法を作ってもらうように issue 立てて報告する必要もあるかもしれない）


---

@t-hamano 
上記の対応策について調べてみてほしいです！

**Comment by ddryo** [comment]
以下のissueで似たようなことが話し合われている気がしますが、しばらく進展がなさそうです。

https://github.com/WordPress/gutenberg/issues/34333

**Comment by t-hamano** [comment]
色々方法を色々探ってみたのですが、以下が一番現実的な方法かなと思います。

## 手順1. `admin_enqueue_scripts` でブロックエディターを除外する
 `admin_enqueue_scripts` フック内で、`$hook_suffix` が `'post.php'` または `'post-new.php'` の場合は、`admin.css` を読み込まないようにする
→メインのブロックエディター、iframe内のエディターどちらにも `admin.css` が読み込まれなくなる

## 手順2. `enqueue_block_editor_assets` で別途 `admin.css` をenqueueする

`enqueue_block_editor_assets` でenqueueしたものはiframe内に読み込まれないので、メインのブロックエディターのみに`admin.css` が読み込まれる
→Warningエラーが消える

## 備考

上記二点に加えて、以下のリファクタリングが出来れば現時点では理想的かな。。と考えております。

- `admin.css` から、ブロックエディター関連のスタイルを切り分けて `block-editor.css` みたいなものを新規作成して、上記 `enqueue_block_editor_assets` で `admin.css` の代わりに読み込む。
- もしくは、切り分けたスタイルを以下とマージする。
> 後者のスタイルは引き続きenqueue_block_editor_assetsで読み込む

**Comment by ddryo** [comment]
> enqueue_block_editor_assets でenqueueしたものはiframe内に読み込まれないので、メインのブロックエディターのみにadmin.css が読み込まれる

についてなのですが、警告が出るだけで enqueue_block_editor_assets での読み込みはiframe内でも行われるっぽいです。

**Comment by ddryo** [comment]
ぬ、警告は除外されるようです

https://github.com/WordPress/gutenberg/pull/37937

**Comment by ddryo** [comment]
んん、ということは、enqueue_block_editor_assets関連はそのままで良いかもしれません。

動的なCSSをadmin_headで出力していた部分のみを`wp_add_inline_style( 'wp-edit-blocks' )`するだけで良さそうです。

**Comment by t-hamano** [comment]
すいません、こちらの勘違いだったかもです。
ちょっとこんがらがってきましたが、まとめると以下のような感じでしょうか？

- `admin_enqueue_scripts` や `enqueue_block_editor_assets` で `wp_enqueue_style` したものは、メインのエディターとiframeのエディター両方に適用される
- 現状はブラウザでWarningエラーが出るがたぶん5.9正式リリースでは出なくなる
- なので、`add_editor_style` は無理に使う必要はない

**Comment by t-hamano** [comment]
Arkheのテストをしていて気づいたのですが、

```php
wp_enqueue_style( 'swell_block_style', T_DIRE_URI . '/assets/css/editor_style.css', [], SWELL_VERSION );
wp_add_inline_style( 'swell_block_style', $custom_format_css );
```
の部分で、ちゃんとiframe内にインラインCSSも出力されていました。
`enqueue_block_editor_assets` の警告が無くなり、 `swell_block_style` も今の読み込み方のままでよくなるので、`admin_head` で出力しているものを上記 `wp_add_inline_style` にマージするだけでよさそうです。

**Comment by ddryo** [comment]
> ちょっとこんがらがってきましたが、まとめると以下のような感じでしょうか？

ですね！


> Arkheのテストをしていて気づいたのですが...

あー確かにそうですね！
`'admin_head'`での出力はSWELLの設定ページやクラシックエディターに必要なのでそうしてたのですが、ブロックエディターかどうかの判定を追加して、ブロックエディターでは`'enqueue_block_editor_assets'`から`'wp_add_inline_style()'`する感じで試してみます。

**Comment by ddryo** [comment]
【まとめ】

- `enqueue_block_editor_assets`や`admin_enqueue_scripts`で読み込んだCSSは、5.9-RC3時点では`.wp-block`などのセレクタが使われているもののみiframe内に読み込まれる。

## インラインCSSについて
- admin_headで出力したものは読み込まれない（もしかしたらこれも`.wp-block`を含んでいれば読み込まれれるかも）。
- 読み込まれているCSSのハンドル名に対して`wp_add_inline_style()`すれば普通に読み込める。
- 依存先のCSSファイルがない場合はコアのCSS（`'wp-edit-blocks'`など）に対して紐付ければ読み込める。
