### ISSUE TITLE
ブロックエディターでのJavaScript読み込みエラー（旧ブロック）

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#90]
`/wp-content/themes/SWELL/build/blocks/old-blocks/index.js` が404となる。
ビルド対象に含めるか、enqueueをやめるかどちらかで改善されると思います。

**Comment by ddryo** [comment]
あー、すみません！これローカルwebpackファイルにだけ書いていて、近々完全削除予定ですので放置で大丈夫です！

**Comment by ddryo** [comment]
#86 のときに解決予定です。
