### ISSUE TITLE
エディター側にカスタマイザーの「フォント設定」が反映されない

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#91]
- ベースとなるフォント
- フォントサイズ

の二点がエディター側に反映されず。

※元々そのような仕様でしたら、クローズで結構です。

**Comment by ddryo** [comment]
@t-hamano 
これも #54 と同じ不具合で、少し前にCSSを調整した時からうまく反映されていなかったようです。僕の方で修正しておきます！
