### ISSUE TITLE
エディターでページ表示時にブラウザコンソールエラー

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#92]
「SWELL設定」パネルを開いた状態で、エディター上でブラウザリロードをかけると、ブラウザコンソールエラーが出る。

https://user-images.githubusercontent.com/54422211/149088365-be7af1ca-ec5c-4c4f-90b7-212e33e43d53.mp4

おそらく、swellStoreから設定を取得されるまでの間、CheckboxControlのcheckedがundefinedになるからだと思います。

```javascript
checked={swellBlockSettings?.show_device_toolbtn ?? false}
```

みたいにすれば改善すると思います。

参考：https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining#null_%E5%90%88%E4%BD%93%E6%BC%94%E7%AE%97%E5%AD%90%E3%81%A8%E5%85%B1%E3%81%AB%E4%BD%BF%E3%81%86

**Comment by ddryo** [comment]
これ5.9の話ですかね？

**Comment by t-hamano** [comment]
5.8でも発生しました。

**Comment by ddryo** [comment]
承知しました！

**Comment by ddryo** [comment]
僕の環境ではこのエラーを再現できなかったので、浜野さんの方で`?.`で修正してみていただければと思います...！

**Comment by t-hamano** [comment]
@ddryo 
了解しました！
こちらWarningエラーなので、`SCRIPT_DEBUG` がオフだと出ないと思います。

※Warningエラーなので動作には基本影響は無いですが、細かいスクリプトエラーをチェックする時はオンにしておくと便利です...！

**Comment by ddryo** [comment]
おお、なるほどです。
SCRIPT_DEBUGを今知りました...w

WP_DEBUGしかオンにしていなかったので後でもう一度確認してみます！

**Comment by ddryo** [comment]
checkboxに`undefined`や`null`が渡されるとuncontrolledと判定されることが原因で、`?.`を使うだけでは`null`が渡って変わらなかったので、falseを渡すようにして解決できました。

参考: https://blog.mitsuruog.info/2017/09/react-uncontrolled-input
