### ISSUE TITLE
リッチテキスト：「書式セット」適用時、見え方が異なる

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#96]
「書式セット」をインラインテキストに適用した時、`mark` タグが付与され、ブラウザのデフォルト背景色（`yellow`）が当たってしまう。
記事を保存・リロードすると、`mark` タグが消えて正常なスタイルで表示される。

![capture](https://user-images.githubusercontent.com/54422211/149122780-5c9b7357-9fa6-4f8d-ae42-58990354bcfd.png)

**Comment by t-hamano** [comment]
インラインテキストカラーを適用した時のタグが、`span` から `mark` に変わった事が関係していそう。
https://github.com/WordPress/gutenberg/pull/34680/files#diff-6ef6519967765b9d4a49b27938bf474f58270c38d8f5358cf4c878c97e2b4276R122

**Comment by ddryo** [comment]
[reopen]
フロント側にも修正が必要なのと、一応セレクタは`mark.has-inline-coloe`にする。
