### ISSUE TITLE
<FormatPopover>から`components-inline-color-popover`クラスを削除する

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#97]
`components-inline-color-popover`クラスを使っていた理由が「paddingが当たること」だったが、#94 の通り5.9からはpaddingが消えてしまうので `components-inline-color-popover` を使う理由がなくなった。

`components-inline-color-popover`を消して 6155d7f で追加された `swell-format-popover` だけにする。

**Comment by t-hamano** [comment]
こちら対応します！
